name: flutter_application_1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Untuk autentikasi dan API dari Laravel
  http: ^1.6.0
  shared_preferences: ^2.3.2

  # Untuk akses lokasi
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  permission_handler: ^12.0.1

  # Untuk tampilan dan aset
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.0
  intl: ^0.20.2
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo_lazuardi.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/logo_lazuardi.png
    - assets/images/google_logo.png
    - assets/images/facebook_logo.png
    - assets/images/logo_lazuardi_noText.png
    - assets/images/icons/daftar_siswa.png
    - assets/images/icons/lencana.png
    - assets/images/icons/tampilan_profile_tutor.png
    - assets/images/icons/ulasan.png
    - assets/images/icons/lock_icon.png
    - assets/images/icons/sidebar/
    - assets/images/icons/sidebar/evaluasi_icon.png
    - assets/images/icons/profile/
    - assets/images/icons/profile/profile_default.png
